language: node_js
env:
  - AZURE_REPO_URL="https://webcatdeveldeploy@webcatdevel.scm.azurewebsites.net:443/webcatdevel.git"
node_js:
  - "4"
branches:
  only:
    - master
before_script:
  - npm install -g gulp
script:
  - npm run build
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master