language: node_js
node_js:
  - "4"
branches:
  only:
    - master
before_script:
  - npm install -g gulp
  - chmod u+x scripts/deploy.sh
script:
  - npm run build
after_success:
  - gulp deploy-remote --repo AZURE_REPO_URL