language: node_js
node_js:
  - "0.10"
branches:
  only:
    - master
before_script:
  - npm install -g gulp
script:
  - gulp
after_success:
  "gulp deploy --user \"$FTP_USER\" --password $FTP_PASSWORD --host $FTP_SITE"