language: node_js
env:
  - AZURE_REPO_URL="https://webcatdeveldeploy@webcatdevel.scm.azurewebsites.net:443/webcatdevel.git"
node_js:
  - "4"
branches:
  only:
    - master
before_script:
  - npm install -g gulp
  - chmod u+x script/deploy.sh
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master