language: node_js
node_js:
  - "0.10"
branches:
  only:
    - master
before_script:
  - npm install -g gulp
  - gulp build
before_deploy:
  - chmod +x before_deploy.sh
  - ./before_deploy.sh
deploy:
  provider: azure_web_apps
  on:
    master
  skip_cleanup: true
  username: "WebCatDev\nerdcats"
  password: "Welovecats"
  site: "WebCatDev"