language: node_js
node_js:
  - "0.10"
branches:
  only:
    - master
deploy:
  provider: azure_web_apps
  on:
    branch: master
  skip_cleanup: true
  username: "nerdcats"
  password: "Welovecats"
  site: "WebCatDev"